name: Dr G Films
favicon: null
layout_spectrum: 1
typography_spectrum: 0.2511
title: Dr G Films
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2c6e90'
    - '#19475e'
    - '#f0ffff'
    - '#a6c8d5'
    - '#81a5b5'
  brandStrength: 0.002449841
  lightness: 0.1972373
  saturation: 0.5440324
  rhythmicContrast: 0.5561799
purpose: []
